version: '3.1'

services:
  vue:
    container_name: mstaff-micro__front-vue-2__dev__vue
    build: docker/dev
    working_dir: /application
    ports:
      - '22000:8080'
    volumes:
      - .:/application
    networks:
      - mstaff-micro.network

networks:
  mstaff-micro.network:
    external: true